//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ietf.org/rfc/rfc2426.txt", IsNullable=false)]
public partial class vcard {
    
    private string fnField;
    
    private vcardN nField;
    
    private string nicknameField;
    
    private string photoField;
    
    private System.DateTime bdayField;
    
    private bool bdayFieldSpecified;
    
    private vcardAdr adrField;
    
    private vcardLabel labelField;
    
    private vcardTel[] telField;
    
    private vcardEmail[] emailField;
    
    private string mailerField;
    
    private string tzField;
    
    private vcardGeo geoField;
    
    private string titleField;
    
    private string roleField;
    
    private string logoField;
    
    private string agentField;
    
    private vcardOrg orgField;
    
    private string[] categoryField;
    
    private string noteField;
    
    private System.DateTime revField;
    
    private bool revFieldSpecified;
    
    private string sortstringField;
    
    private string soundField;
    
    private vcardUid uidField;
    
    private string urlField;
    
    private classtype classField;
    
    private bool classFieldSpecified;
    
    private vcardKey keyField;
    
    /// <remarks/>
    public string fn {
        get {
            return this.fnField;
        }
        set {
            this.fnField = value;
        }
    }
    
    /// <remarks/>
    public vcardN n {
        get {
            return this.nField;
        }
        set {
            this.nField = value;
        }
    }
    
    /// <remarks/>
    public string nickname {
        get {
            return this.nicknameField;
        }
        set {
            this.nicknameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string photo {
        get {
            return this.photoField;
        }
        set {
            this.photoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime bday {
        get {
            return this.bdayField;
        }
        set {
            this.bdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bdaySpecified {
        get {
            return this.bdayFieldSpecified;
        }
        set {
            this.bdayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public vcardAdr adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
    
    /// <remarks/>
    public vcardLabel label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tel")]
    public vcardTel[] tel {
        get {
            return this.telField;
        }
        set {
            this.telField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("email")]
    public vcardEmail[] email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string mailer {
        get {
            return this.mailerField;
        }
        set {
            this.mailerField = value;
        }
    }
    
    /// <remarks/>
    public string tz {
        get {
            return this.tzField;
        }
        set {
            this.tzField = value;
        }
    }
    
    /// <remarks/>
    public vcardGeo geo {
        get {
            return this.geoField;
        }
        set {
            this.geoField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string logo {
        get {
            return this.logoField;
        }
        set {
            this.logoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string agent {
        get {
            return this.agentField;
        }
        set {
            this.agentField = value;
        }
    }
    
    /// <remarks/>
    public vcardOrg org {
        get {
            return this.orgField;
        }
        set {
            this.orgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category")]
    public string[] category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime rev {
        get {
            return this.revField;
        }
        set {
            this.revField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool revSpecified {
        get {
            return this.revFieldSpecified;
        }
        set {
            this.revFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sort-string")]
    public string sortstring {
        get {
            return this.sortstringField;
        }
        set {
            this.sortstringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string sound {
        get {
            return this.soundField;
        }
        set {
            this.soundField = value;
        }
    }
    
    /// <remarks/>
    public vcardUid uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public classtype @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool classSpecified {
        get {
            return this.classFieldSpecified;
        }
        set {
            this.classFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public vcardKey key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardN {
    
    private string familynameField;
    
    private string givennameField;
    
    private string[] additionalnameField;
    
    private string[] honorificprefixField;
    
    private string[] honorificsuffixField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("family-name")]
    public string familyname {
        get {
            return this.familynameField;
        }
        set {
            this.familynameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("given-name")]
    public string givenname {
        get {
            return this.givennameField;
        }
        set {
            this.givennameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("additional-name")]
    public string[] additionalname {
        get {
            return this.additionalnameField;
        }
        set {
            this.additionalnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("honorific-prefix")]
    public string[] honorificprefix {
        get {
            return this.honorificprefixField;
        }
        set {
            this.honorificprefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("honorific-suffix")]
    public string[] honorificsuffix {
        get {
            return this.honorificsuffixField;
        }
        set {
            this.honorificsuffixField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardAdr {
    
    private string postofficeboxField;
    
    private string extendedaddressField;
    
    private string streetaddressField;
    
    private string localityField;
    
    private string regionField;
    
    private string postalcodeField;
    
    private string countrynameField;
    
    private adrtype typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("post-office-box")]
    public string postofficebox {
        get {
            return this.postofficeboxField;
        }
        set {
            this.postofficeboxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("extended-address")]
    public string extendedaddress {
        get {
            return this.extendedaddressField;
        }
        set {
            this.extendedaddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("street-address")]
    public string streetaddress {
        get {
            return this.streetaddressField;
        }
        set {
            this.streetaddressField = value;
        }
    }
    
    /// <remarks/>
    public string locality {
        get {
            return this.localityField;
        }
        set {
            this.localityField = value;
        }
    }
    
    /// <remarks/>
    public string region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("postal-code")]
    public string postalcode {
        get {
            return this.postalcodeField;
        }
        set {
            this.postalcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("country-name")]
    public string countryname {
        get {
            return this.countrynameField;
        }
        set {
            this.countrynameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public adrtype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="adr-type", Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public enum adrtype {
    
    /// <remarks/>
    intl = 1,
    
    /// <remarks/>
    dom = 2,
    
    /// <remarks/>
    parcel = 4,
    
    /// <remarks/>
    home = 8,
    
    /// <remarks/>
    work = 16,
    
    /// <remarks/>
    pref = 32,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("dom")]
    dom1 = 64,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardLabel {
    
    private adrtype typeField;
    
    private bool typeFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public adrtype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardTel {
    
    private teltype typeField;
    
    private string valueField;
    
    public vcardTel() {
        this.typeField = teltype.voice;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(teltype.voice)]
    public teltype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="tel-type", Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public enum teltype {
    
    /// <remarks/>
    home = 1,
    
    /// <remarks/>
    msg = 2,
    
    /// <remarks/>
    work = 4,
    
    /// <remarks/>
    pref = 8,
    
    /// <remarks/>
    voice = 16,
    
    /// <remarks/>
    fax = 32,
    
    /// <remarks/>
    cell = 64,
    
    /// <remarks/>
    video = 128,
    
    /// <remarks/>
    pager = 256,
    
    /// <remarks/>
    bbs = 512,
    
    /// <remarks/>
    modem = 1024,
    
    /// <remarks/>
    isdn = 2048,
    
    /// <remarks/>
    pcs = 4096,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardEmail {
    
    private emailtype typeField;
    
    private bool typeFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public emailtype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="email-type", Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public enum emailtype {
    
    /// <remarks/>
    internet = 1,
    
    /// <remarks/>
    x400 = 2,
    
    /// <remarks/>
    pref = 4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardGeo {
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardOrg {
    
    private string organizationnameField;
    
    private string organizationunitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organization-name")]
    public string organizationname {
        get {
            return this.organizationnameField;
        }
        set {
            this.organizationnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organization-unit")]
    public string organizationunit {
        get {
            return this.organizationunitField;
        }
        set {
            this.organizationunitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardUid {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="class-type", Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public enum classtype {
    
    /// <remarks/>
    PUBLIC,
    
    /// <remarks/>
    PRIVATE,
    
    /// <remarks/>
    CONFIDENTIAL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ietf.org/rfc/rfc2426.txt")]
public partial class vcardKey {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
